## Import Libraries

In [28]:
import pandas as pd
import numpy as np

## Import CSV using Pandas

In [5]:
df = pd.read_csv("archive.csv")

print(df)

             Date  Platform Product_Category                   Model_Name  \
0      2020-09-19  Flipkart            Watch  Apple Watch Series 6 (44mm)   
1      2020-09-20  Flipkart            Watch  Apple Watch Series 6 (44mm)   
2      2020-09-23    Amazon            Watch  Apple Watch Series 6 (44mm)   
3      2020-09-23    Amazon            Watch  Apple Watch Series 6 (44mm)   
4      2020-09-24    Amazon            Watch  Apple Watch Series 6 (44mm)   
...           ...       ...              ...                          ...   
79995  2026-07-31  Flipkart           iPhone              iPhone 17 128GB   
79996  2026-07-31  Flipkart           iPhone              iPhone 17 128GB   
79997  2026-07-31    Amazon           iPhone              iPhone 17 128GB   
79998  2026-07-31  Flipkart           iPhone              iPhone 17 128GB   
79999  2026-07-31  Flipkart           iPhone              iPhone 17 128GB   

                 Condition  Launch_Price_USD  Launch_Price_INR  \
0        

## View Dataset

In [6]:
print(df.head())

         Date  Platform Product_Category                   Model_Name  \
0  2020-09-19  Flipkart            Watch  Apple Watch Series 6 (44mm)   
1  2020-09-20  Flipkart            Watch  Apple Watch Series 6 (44mm)   
2  2020-09-23    Amazon            Watch  Apple Watch Series 6 (44mm)   
3  2020-09-23    Amazon            Watch  Apple Watch Series 6 (44mm)   
4  2020-09-24    Amazon            Watch  Apple Watch Series 6 (44mm)   

  Condition  Launch_Price_USD  Launch_Price_INR  Current_Price_USD  \
0       New               429             42042             435.81   
1       New               429             42042             436.49   
2       New               429             42042             422.73   
3       New               429             42042             425.00   
4       New               429             42042             436.22   

   Current_Price_INR  Discount_Pct Sale_Event  Stock_Status  Rating  \
0           43322.41          -1.6        NaN      In Stock     4.7  

In [7]:
print(df.tail())

             Date  Platform Product_Category       Model_Name  \
79995  2026-07-31  Flipkart           iPhone  iPhone 17 128GB   
79996  2026-07-31  Flipkart           iPhone  iPhone 17 128GB   
79997  2026-07-31    Amazon           iPhone  iPhone 17 128GB   
79998  2026-07-31  Flipkart           iPhone  iPhone 17 128GB   
79999  2026-07-31  Flipkart           iPhone  iPhone 17 128GB   

                 Condition  Launch_Price_USD  Launch_Price_INR  \
79995                  New               849             83202   
79996                  New               849             83202   
79997  Renewed/Refurbished               849             83202   
79998  Renewed/Refurbished               849             83202   
79999                  New               849             83202   

       Current_Price_USD  Current_Price_INR  Discount_Pct Sale_Event  \
79995             861.39           82894.76          -1.5        NaN   
79996             832.50           81159.39           1.9        NaN

In [8]:
print(df.shape)

(80000, 14)


In [9]:
print(df.columns)

Index(['Date', 'Platform', 'Product_Category', 'Model_Name', 'Condition',
       'Launch_Price_USD', 'Launch_Price_INR', 'Current_Price_USD',
       'Current_Price_INR', 'Discount_Pct', 'Sale_Event', 'Stock_Status',
       'Rating', 'Reviews_Count'],
      dtype='object')


In [10]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Date               80000 non-null  object 
 1   Platform           80000 non-null  object 
 2   Product_Category   80000 non-null  object 
 3   Model_Name         80000 non-null  object 
 4   Condition          80000 non-null  object 
 5   Launch_Price_USD   80000 non-null  int64  
 6   Launch_Price_INR   80000 non-null  int64  
 7   Current_Price_USD  80000 non-null  float64
 8   Current_Price_INR  80000 non-null  float64
 9   Discount_Pct       80000 non-null  float64
 10  Sale_Event         6649 non-null   object 
 11  Stock_Status       80000 non-null  object 
 12  Rating             80000 non-null  float64
 13  Reviews_Count      80000 non-null  int64  
dtypes: float64(4), int64(3), object(7)
memory usage: 8.5+ MB
None


In [11]:
print(df.describe())

       Launch_Price_USD  Launch_Price_INR  Current_Price_USD  \
count      80000.000000      80000.000000       80000.000000   
mean         963.959125      94467.994250         782.769855   
std          470.086413      46068.468464         461.673970   
min          329.000000      32242.000000         109.930000   
25%          599.000000      58702.000000         432.930000   
50%          799.000000      78302.000000         699.740000   
75%         1199.000000     117502.000000         989.112500   
max         1999.000000     195902.000000        2038.970000   

       Current_Price_INR  Discount_Pct        Rating  Reviews_Count  
count       80000.000000  80000.000000  80000.000000   80000.000000  
mean        74628.342439     21.418826      4.450099    2405.995925  
std         45117.872172     16.697310      0.269782    1973.630852  
min          9157.680000     -2.000000      3.800000      10.000000  
25%         41686.835000      6.700000      4.300000     896.000000  
50%

## Creating a Multidimensional Array

In [12]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


## Accessing Values Using Index Numbers

In [13]:
print(arr[0][0])

10


In [14]:
print(arr[1][2])

60


In [15]:
print(arr[2][1])

80


## Performing Mathematical Operations:

##Addition:

In [21]:
print(arr + 10)

[[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]


## Multiplication:

In [22]:
print(arr * 2)

[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]


## Division:

In [23]:
print(arr / 5)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


## Square:

In [24]:
print(arr ** 2)

[[ 100  400  900]
 [1600 2500 3600]
 [4900 6400 8100]]


## 15 NumPy Methods

In [27]:
#1. shape
print(arr.shape)

#2. ndim
print(arr.ndim)

#3. size
print(arr.size)

#4. dtype
print(arr.dtype)

#5. reshape
print(arr.reshape(1,9))

#6. flatten
print(arr.flatten())

#7. transpose
print(arr.T)

#8. sum
print(np.sum(arr))

#9. mean
print(np.mean(arr))

#10. max
print(np.max(arr))

#11. min
print(np.min(arr))

#12. sort
x = np.array([8,2,9,4])
print(np.sort(x))

#13. sqrt
print(np.sqrt(arr))

#14. unique
x = np.array([1,2,2,3,4,4,5])
print(np.unique(x))

#15. concatenate
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

(3, 3)
2
9
int64
[[10 20 30 40 50 60 70 80 90]]
[10 20 30 40 50 60 70 80 90]
[[10 40 70]
 [20 50 80]
 [30 60 90]]
450
50.0
90
10
[2 4 8 9]
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]
 [8.36660027 8.94427191 9.48683298]]
[1 2 3 4 5]
[1 2 3 4 5 6]
